# Generated by Django 5.2 on 2026-09-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='client_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clientorg'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.provider'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grant',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='users.clientorg'),
        ),
        migrations.AddField(
            model_name='grant',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='access.consumer'),
        ),
        migrations.AddField(
            model_name='grant',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grant',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='providers.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together={('consumer', 'client_org', 'provider')},
        ),
    ]
