# Generated by Django 5.2 on 2026-09-07 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_grantrequest'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grantrequest',
            name='client_org',
        ),
        migrations.RemoveField(
            model_name='grantrequest',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='grantrequest',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='grantrequest',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='grantrequest',
            name='requested_by',
        ),
        migrations.AddField(
            model_name='consumer',
            name='client_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.clientorg'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='access.consumer')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.DeleteModel(
            name='GrantRequest',
        ),
    ]
