# Generated by Django 5.2 on 2026-09-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
