# Generated by Django 5.2 on 2026-09-03 14:47

import connections.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reconnect', 'Needs reconnect'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['client_org', 'provider'],
            },
        ),
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_refresh_token', connections.fields.EncryptedTextField(blank=True)),
                ('enc_access_token', connections.fields.EncryptedTextField(blank=True)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
