# Generated by Django 5.2 on 2026-09-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='users.clientorg'),
        ),
        migrations.AddField(
            model_name='connection',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='providers.provider'),
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='client_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientorg'),
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oauthstate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AddField(
            model_name='tokenset',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='connections.connection'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('client_org', 'provider')},
        ),
    ]
