# Generated by Django 5.2 on 2026-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
