# Generated by Django 5.2 on 2026-09-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_oauthstate_meta'),
        ('providers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('client_org', 'provider', 'external_account_id')},
        ),
    ]
