# Generated by Django 5.2 on 2026-09-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_migrate_tokens_to_credentials'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenSet',
        ),
    ]
